[project]
name = "finalproj"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10, <3.11"
dependencies = [
    "pandas-stubs~=2.3.3",
    "scikit-learn>=1.7.2",
]
